### ISSUE TITLE
Problem retrieving the repository index file for service 'container-suseconnect'

### ISSUE THREAD

**Issue by urban-it-solutions** [SUSE/zypper-docker#85] opened 2015-12-09 09:48 UTC
Don´t know, if it is a problem of zypper-docker or sle2docker or the sle2docker-image....

zypper-docker lp suse/sles12

Refreshing service 'container-suseconnect'.
Problem retrieving the repository index file for service 'container-suseconnect':
[container-suseconnect|file:/usr/lib/zypp/plugins/services/container-suseconnect]
Warning: Skipping service 'container-suseconnect' because of the above error.
Warning: There are no enabled repositories defined.
Use 'zypper addrepo' or 'zypper modifyrepo' commands to add or enable repositories.

zypper-docker-1.1.1-8.1.x86_64

sle2docker-0.4.2-14.3.x86_64

Image:
 - sles12-docker.x86_64-1.1.0-Build10.1

Seems like the SCCcredentials is not injected into the image. When I create a new one with the following Dockerfile-Command:

ADD SCCcredentials /etc/zypp/credentials.d/

It works....

**Comment by flavio** [comment] 2015-12-09 10:34
This is a duplicate of https://github.com/SUSE/sle2docker/issues/17

**Closed by flavio** 2015-12-09 10:34 UTC
